Project chatalyst {
  database_type: 'MySQL'
  Note: 'Collage final year project where we are making a chat application with bots.'
}

Table Users {
    id char(32) [pk]
    username text
    picture text
    isBot boolean
}

Table Channels {
    id bigint [pk,increment]
    name text
    picture text
    lastMessage bigint
}

Table Messages {
    id bigint [pk,increment]
    channelId bigint
    sentBy char(32)
    sentOn timestamp
    content text
}

// Relations
Ref Users_Channels: Users.id <> Channels.id
Ref: Messages.channelId > Channels.id
