Table Users {
    userId char(32) [pk]
    username text
    picture text
}

Table Channels {
    chanId bigint [pk]
    lastMessage bigint
}

Table Messages {
    msgId bigint [pk]
    chanId bigint
    sentBy char(32)
    sentOn timestamp
}

// Relations
Ref Users_Channels: Channels.chanId <> Users.userId

Ref: Channels.lastMessage - Messages.msgId
Ref: Messages.chanId > Channels.chanId
Ref: Messages.sentBy > Users.userId
